/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace SupplyChainProvenance {
      
    export type ProductStruct = {prodId: BigNumberish, producer: AddressLike, producerBatchId: BigNumberish, ipfsHash: string, expirationDate: BigNumberish, currentBatchId: BigNumberish, currentStatus: BigNumberish, currentOwner: AddressLike, parentBatchId: BigNumberish}

    export type ProductStructOutput = [prodId: bigint, producer: string, producerBatchId: bigint, ipfsHash: string, expirationDate: bigint, currentBatchId: bigint, currentStatus: bigint, currentOwner: string, parentBatchId: bigint] & {prodId: bigint, producer: string, producerBatchId: bigint, ipfsHash: string, expirationDate: bigint, currentBatchId: bigint, currentStatus: bigint, currentOwner: string, parentBatchId: bigint }
  
    }

  export interface SupplyChainProvenanceInterface extends Interface {
    getFunction(nameOrSignature: "admin" | "assignRole" | "createProduct" | "getProduct" | "markReadyToShip" | "passWarehouseQualityCheck" | "placeInStore" | "productLedger" | "purchaseProduct" | "receiveAtWarehouse" | "receiveReturnedFromRetailer" | "retailerReceiveProduct" | "returnToWarehouse" | "rolesMapping" | "shipToRetailer" | "storeInWarehouse" | "verifyProduct"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ProductCreated" | "ProductOwnershipTransferred" | "ProductStatusChanged" | "RoleAssigned"): EventFragment;

    encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'assignRole', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createProduct', values: [BigNumberish, BigNumberish, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProduct', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'markReadyToShip', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'passWarehouseQualityCheck', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'placeInStore', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'productLedger', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'purchaseProduct', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'receiveAtWarehouse', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'receiveReturnedFromRetailer', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'retailerReceiveProduct', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'returnToWarehouse', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'rolesMapping', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'shipToRetailer', values: [BigNumberish, AddressLike, string]): string;
encodeFunctionData(functionFragment: 'storeInWarehouse', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'verifyProduct', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'assignRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createProduct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProduct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markReadyToShip', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'passWarehouseQualityCheck', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'placeInStore', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'productLedger', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'purchaseProduct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'receiveAtWarehouse', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'receiveReturnedFromRetailer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'retailerReceiveProduct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'returnToWarehouse', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rolesMapping', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'shipToRetailer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'storeInWarehouse', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyProduct', data: BytesLike): Result;
  }

  
    export namespace ProductCreatedEvent {
      export type InputTuple = [prodId: BigNumberish, producer: AddressLike, ipfsHash: string];
      export type OutputTuple = [prodId: bigint, producer: string, ipfsHash: string];
      export interface OutputObject {prodId: bigint, producer: string, ipfsHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProductOwnershipTransferredEvent {
      export type InputTuple = [prodId: BigNumberish, previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [prodId: bigint, previousOwner: string, newOwner: string];
      export interface OutputObject {prodId: bigint, previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProductStatusChangedEvent {
      export type InputTuple = [prodId: BigNumberish, newStatus: BigNumberish, updatedBy: AddressLike, ipfsHash: string];
      export type OutputTuple = [prodId: bigint, newStatus: bigint, updatedBy: string, ipfsHash: string];
      export interface OutputObject {prodId: bigint, newStatus: bigint, updatedBy: string, ipfsHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAssignedEvent {
      export type InputTuple = [user: AddressLike, role: BigNumberish];
      export type OutputTuple = [user: string, role: bigint];
      export interface OutputObject {user: string, role: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SupplyChainProvenance extends BaseContract {
    
    connect(runner?: ContractRunner | null): SupplyChainProvenance;
    waitForDeployment(): Promise<this>;

    interface: SupplyChainProvenanceInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    assignRole: TypedContractMethod<
      [user: AddressLike, role: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createProduct: TypedContractMethod<
      [prodId: BigNumberish, producerBatchId: BigNumberish, ipfsHash: string, expirationDate: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getProduct: TypedContractMethod<
      [prodId: BigNumberish, ],
      [SupplyChainProvenance.ProductStructOutput],
      'view'
    >
    

    
    markReadyToShip: TypedContractMethod<
      [prodId: BigNumberish, ipfsHash: string, ],
      [void],
      'nonpayable'
    >
    

    
    passWarehouseQualityCheck: TypedContractMethod<
      [prodId: BigNumberish, ipfsHash: string, ],
      [void],
      'nonpayable'
    >
    

    
    placeInStore: TypedContractMethod<
      [prodId: BigNumberish, ipfsHash: string, ],
      [void],
      'nonpayable'
    >
    

    
    productLedger: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, string, bigint, bigint, bigint, string, bigint] & {prodId: bigint, producer: string, producerBatchId: bigint, ipfsHash: string, expirationDate: bigint, currentBatchId: bigint, currentStatus: bigint, currentOwner: string, parentBatchId: bigint }],
      'view'
    >
    

    
    purchaseProduct: TypedContractMethod<
      [prodId: BigNumberish, ipfsHash: string, ],
      [void],
      'nonpayable'
    >
    

    
    receiveAtWarehouse: TypedContractMethod<
      [prodId: BigNumberish, ipfsHash: string, ],
      [void],
      'nonpayable'
    >
    

    
    receiveReturnedFromRetailer: TypedContractMethod<
      [prodId: BigNumberish, ipfsHash: string, ],
      [void],
      'nonpayable'
    >
    

    
    retailerReceiveProduct: TypedContractMethod<
      [prodId: BigNumberish, ipfsHash: string, ],
      [void],
      'nonpayable'
    >
    

    
    returnToWarehouse: TypedContractMethod<
      [prodId: BigNumberish, ipfsHash: string, ],
      [void],
      'nonpayable'
    >
    

    
    rolesMapping: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    shipToRetailer: TypedContractMethod<
      [prodId: BigNumberish, retailer: AddressLike, ipfsHash: string, ],
      [void],
      'nonpayable'
    >
    

    
    storeInWarehouse: TypedContractMethod<
      [prodId: BigNumberish, ipfsHash: string, ],
      [void],
      'nonpayable'
    >
    

    
    verifyProduct: TypedContractMethod<
      [prodId: BigNumberish, ],
      [SupplyChainProvenance.ProductStructOutput],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'assignRole'): TypedContractMethod<
      [user: AddressLike, role: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createProduct'): TypedContractMethod<
      [prodId: BigNumberish, producerBatchId: BigNumberish, ipfsHash: string, expirationDate: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getProduct'): TypedContractMethod<
      [prodId: BigNumberish, ],
      [SupplyChainProvenance.ProductStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'markReadyToShip'): TypedContractMethod<
      [prodId: BigNumberish, ipfsHash: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'passWarehouseQualityCheck'): TypedContractMethod<
      [prodId: BigNumberish, ipfsHash: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'placeInStore'): TypedContractMethod<
      [prodId: BigNumberish, ipfsHash: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'productLedger'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, string, bigint, bigint, bigint, string, bigint] & {prodId: bigint, producer: string, producerBatchId: bigint, ipfsHash: string, expirationDate: bigint, currentBatchId: bigint, currentStatus: bigint, currentOwner: string, parentBatchId: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'purchaseProduct'): TypedContractMethod<
      [prodId: BigNumberish, ipfsHash: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'receiveAtWarehouse'): TypedContractMethod<
      [prodId: BigNumberish, ipfsHash: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'receiveReturnedFromRetailer'): TypedContractMethod<
      [prodId: BigNumberish, ipfsHash: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'retailerReceiveProduct'): TypedContractMethod<
      [prodId: BigNumberish, ipfsHash: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'returnToWarehouse'): TypedContractMethod<
      [prodId: BigNumberish, ipfsHash: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rolesMapping'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'shipToRetailer'): TypedContractMethod<
      [prodId: BigNumberish, retailer: AddressLike, ipfsHash: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'storeInWarehouse'): TypedContractMethod<
      [prodId: BigNumberish, ipfsHash: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyProduct'): TypedContractMethod<
      [prodId: BigNumberish, ],
      [SupplyChainProvenance.ProductStructOutput],
      'view'
    >;

    getEvent(key: 'ProductCreated'): TypedContractEvent<ProductCreatedEvent.InputTuple, ProductCreatedEvent.OutputTuple, ProductCreatedEvent.OutputObject>;
getEvent(key: 'ProductOwnershipTransferred'): TypedContractEvent<ProductOwnershipTransferredEvent.InputTuple, ProductOwnershipTransferredEvent.OutputTuple, ProductOwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ProductStatusChanged'): TypedContractEvent<ProductStatusChangedEvent.InputTuple, ProductStatusChangedEvent.OutputTuple, ProductStatusChangedEvent.OutputObject>;
getEvent(key: 'RoleAssigned'): TypedContractEvent<RoleAssignedEvent.InputTuple, RoleAssignedEvent.OutputTuple, RoleAssignedEvent.OutputObject>;

    filters: {
      
      'ProductCreated(uint256,address,string)': TypedContractEvent<ProductCreatedEvent.InputTuple, ProductCreatedEvent.OutputTuple, ProductCreatedEvent.OutputObject>;
      ProductCreated: TypedContractEvent<ProductCreatedEvent.InputTuple, ProductCreatedEvent.OutputTuple, ProductCreatedEvent.OutputObject>;
    

      'ProductOwnershipTransferred(uint256,address,address)': TypedContractEvent<ProductOwnershipTransferredEvent.InputTuple, ProductOwnershipTransferredEvent.OutputTuple, ProductOwnershipTransferredEvent.OutputObject>;
      ProductOwnershipTransferred: TypedContractEvent<ProductOwnershipTransferredEvent.InputTuple, ProductOwnershipTransferredEvent.OutputTuple, ProductOwnershipTransferredEvent.OutputObject>;
    

      'ProductStatusChanged(uint256,uint8,address,string)': TypedContractEvent<ProductStatusChangedEvent.InputTuple, ProductStatusChangedEvent.OutputTuple, ProductStatusChangedEvent.OutputObject>;
      ProductStatusChanged: TypedContractEvent<ProductStatusChangedEvent.InputTuple, ProductStatusChangedEvent.OutputTuple, ProductStatusChangedEvent.OutputObject>;
    

      'RoleAssigned(address,uint8)': TypedContractEvent<RoleAssignedEvent.InputTuple, RoleAssignedEvent.OutputTuple, RoleAssignedEvent.OutputObject>;
      RoleAssigned: TypedContractEvent<RoleAssignedEvent.InputTuple, RoleAssignedEvent.OutputTuple, RoleAssignedEvent.OutputObject>;
    
    };
  }